### ISSUE TITLE
Original string is changed

### ISSUE THREAD

**Issue by kluverp** [jacketizer/libyuarel#11]
Maybe the Read.me could be updated with the notion that the original string will be modified during the parsing proces?
I noticed my original string after parsing containing only "http" after parsing was done. I still need my original string after parsing, so I pulled a copy using malloc(). 
I assume you do not want a malloc() call in your lib? So you deliberately do not make a local copy, am I right?

**Comment by jacketizer** [comment]
Thanks for the feedback, I will fix it ASAP :-)

**Comment by jacketizer** [comment]
Fixed in commit 463760fb101861d760eae9b46dbf7f8dfaa30179.

**Comment by IamFive** [comment]
modify url string directly will cause problem. how u can free the memory malloced by the URL?
