### ISSUE TITLE
user name/password not work

### ISSUE THREAD

**Issue by programmer131** [jacketizer/libyuarel#3]
Hi!
I tried this library in my Lwip stm32f4 webserver project, it works fine but if add user name/password, then not work, I think need modification for making it work with example mentioned below  
"http://admin:admin@192.168.0.1:8989/path/to/test?query=yes&param1=no#frag=1"

![image](https://cloud.githubusercontent.com/assets/12946496/21386955/3f860ad4-c797-11e6-8072-3619fa6c8dc0.png)

**Comment by jacketizer** [comment]
Hello, the library does not support credentials in the URL for now, but let me fix it and it will probably be done by the weekend :-D Please, let me know if there any more problems or improvements :+1:

**Comment by programmer131** [comment]
Thanks for your quick response, I needed it today, modified it myself and it works well now,
have added comment where I added my code.




![image](https://cloud.githubusercontent.com/assets/12946496/21391956/94030086-c7af-11e6-84ba-89936fc4dd3d.png)


[yuarel c file.txt](https://github.com/jacketizer/libyuarel/files/666505/yuarel.c.file.txt)
[yuarel h file.txt](https://github.com/jacketizer/libyuarel/files/666506/yuarel.h.file.txt)

sorry no experience with github, codes given in text files.

**Comment by jacketizer** [comment]
Great :-) I can fix the code so that it conforms to the existing code style and :) Thank you :+1:

**Comment by zgoda** [comment]
Any chance to have this merged & resolved? I'd prefer to use this library as git submodule without doing my own fork.

**Comment by jacketizer** [comment]
Sorry, I have been busy and forgot about it :-( I will look at it tonight
:-)

Best regards
Jack

**Comment by jacketizer** [comment]
Sorry for the delay, it is now fixed on master :-)
